/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-27 15:01:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patientLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1714229182165L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1714229182147L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>OBBMS - Save The Lifes</title>\n");
      out.write("\n");
      out.write("        <!-- font awesome -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"\n");
      out.write("              integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\"\n");
      out.write("              crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("        <!--Bootstrap cdn-->\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("        <link href=\"static/css/style.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"static/img/logo.avif\" rel=\"icon\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <nav style=\"background-color: #FF0018;\" class=\"navbar navbar-expand-md navbar-dark fixed-top\">\n");
      out.write("            <div class=\"container-fluid d-flex justify-content-evenly\">\n");
      out.write("                <!-- Title -->\n");
      out.write("                <div class=\"navbar-brand fs-3 me-auto\"><i class=\"fas fa-heartbeat\"></i>&nbsp; Online Blood Bank Management System &nbsp;<i class=\"fas fa-heartbeat\"></i></div>\n");
      out.write("                <!-- Toggle Button -->\n");
      out.write("                <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("                <!-- Navbar Links -->\n");
      out.write("                <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarCollapse\">\n");
      out.write("                    <div class=\"navbar-collapse collapse w-100 order-3 dual-collapse2\">\n");
      out.write("                        <ul class=\"navbar-nav me-auto mb-2 mb-md-0 justify-content-md-evenly\" style=\"margin-left: 300px;\">\n");
      out.write("                            <li class=\"nav-item ms-4\">\n");
      out.write("                                <a class=\"nav-link t-white fs-5\" href=\"index.jsp\"><i class=\"fas fa-home\"></i>&nbsp; Home</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item ms-4\">\n");
      out.write("                                <a class=\"nav-link t-white fs-5\" href=\"patientLogin.jsp\"><i class=\"fas fa-procedures\"></i>&nbsp; Patient</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item ms-4\">\n");
      out.write("                                <a class=\"nav-link t-white fs-5\" href=\"donarLogin.jsp\"><i class=\"fas fa-user\"></i>&nbsp; Donor</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item ms-4\">\n");
      out.write("                                <a class=\"nav-link t-white fs-5\" href=\"adminLogin.jsp\"><i class=\"fas fa-user-shield\"></i>&nbsp; Admin</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <img src=\"static/img/bg.png\" alt=\"alt\" class=\"position-absolute w-100 h-100 \"/>\n");
      out.write("        ");
      out.write("<div class=\"bg-red text-light fixed-bottom text-center\">\n");
      out.write("    <p class=\"pt-1\"> Made In India &COPY; 2024</p>\n");
      out.write("</div>");
      out.write("\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <main class=\"d-flex align-items-center justify-content-center\" style=\"height:80vh\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-4 offset-md-4\">\n");
      out.write("                        <div class=\"card border-0\">\n");
      out.write("                            <div class=\"card-header bg-red text-light text-center fs-5\">\n");
      out.write("                                <i class=\"fas fa-procedures fa-3x\"></i>&nbsp; \n");
      out.write("                                <p class=\"fw-bold\">Patient Login</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"card-body\">\n");
      out.write("                                <form action=\"patientLogin\" method=\"post\" id=\"patientForm\">\n");
      out.write("                                    <div class=\"mb-3\">\n");
      out.write("                                        <label for=\"mobno\" class=\"form-label fw-semibold\">Mobile No</label>\n");
      out.write("                                        <input type=\"tel\" class=\"form-control\" id=\"mobno\" name=\"mobno\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"mb-3\">\n");
      out.write("                                        <label for=\"exampleInputPassword1\" class=\"form-label fw-semibold\">Password</label>\n");
      out.write("                                        <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" name=\"password\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"container text-center my-3\" style=\"display: none\" id=\"loader\">\n");
      out.write("                                        <span class=\"fa fa-refresh fa-spin fa-3x\" style=\"color: red\"></span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"text-center\">\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-danger fw-bold\" id=\"login-btn\">Login</button>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                                <br>\n");
      out.write("                                <div class=\"text-center\" id=\"sign-btn\">\n");
      out.write("                                    <p class=\"fw-bold\">Does not have an account ? </p>\n");
      out.write("                                    <p>   <a href=\"patientSignup.jsp\" class=\"text-danger text-decoration-none\">Click here to register</a>\n");
      out.write("                                    </p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("        <script src=\"static/js/patientLogin.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
