/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-28 03:57:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template.donar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.helper.*;
import com.entities.Donar;
import java.sql.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import com.entities.Donar;
import com.helper.IdProvider;

public final class donarDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/template/donar/../../footer.html", Long.valueOf(1714229182147L));
    _jspx_dependants.put("/template/donar/../../header.jsp", Long.valueOf(1714229182147L));
    _jspx_dependants.put("/template/donar/donarBase.jsp", Long.valueOf(1714229182248L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.helper");
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.helper.IdProvider");
    _jspx_imports_classes.add("com.entities.Donar");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>OBBMS - Save The Lifes</title>\n");
      out.write("\n");
      out.write("        <!-- font awesome -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"\n");
      out.write("              integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\"\n");
      out.write("              crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("        <!--Bootstrap cdn-->\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("        <link href=\"../../static/css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"../../static/img/logo.avif\" rel=\"icon\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <nav style=\"background-color: #FF0018;\" class=\"navbar navbar-expand-md navbar-dark fixed-top\">\n");
      out.write("            <div class=\"container-fluid d-flex justify-content-evenly\">\n");
      out.write("                <!-- Title -->\n");
      out.write("                <div class=\"navbar-brand fs-3 me-auto\"><i class=\"fas fa-heartbeat\"></i>&nbsp; Online Blood Bank Management System &nbsp;<i class=\"fas fa-heartbeat\"></i></div>\n");
      out.write("                <!-- Navbar Links -->\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li class=\"nav-item ms-5\">\n");
      out.write("                        <a class=\"nav-link fs-5 me-5\" style=\"color: white;\" data-bs-toggle=\"modal\" data-bs-target=\"#profileModal\" href=\"#?\"><i class=\"fas fa-user-circle\"></i> Profile</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <!-- Modal -->\n");
      out.write("        <div class=\"modal fade\" id=\"profileModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog \">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header bg-red\">\n");
      out.write("                        <h1 class=\"modal-title fs-5 text-light text-center\" id=\"exampleModalLabel\"><i class=\"fas fa-user-circle fs-5\"></i> Donar Profile</h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close bg-light\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        ");

                            Donar donar = (Donar) session.getAttribute("currentDonar");
                        
      out.write("\n");
      out.write("                        <table class=\"table\">\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Name : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getfName() + " " + donar.getlName());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Address : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getAddress());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Mobile No : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getMobno());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Blood Group : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getBloodgroup());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <div class=\"d-flex justify-content-evenly\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#editModal\"><i class=\"fas fa-solid fa-user-pen\"></i> Edit</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-outline-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#passwordModal\"><i class=\"fas fa-solid fa-key\"></i> Change Password</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" onclick=\"logout('donarLogin')\"><i class=\"fas fa-sign-out-alt\"></i> Log out</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"modal fade\" id=\"editModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog \">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header bg-red\">\n");
      out.write("                        <h1 class=\"modal-title fs-5 text-light text-center\" id=\"exampleModalLabel\"><i class=\"fas fa-solid fa-user-pen fs-5\"></i> Edit Details </h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close bg-light\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <form action=\"../../editProfile\" method=\"post\" id=\"editProfile\">\n");
      out.write("                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( IdProvider.getDonarId(donar));
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"userType\" id=\"userType\" value=\"donar\">\n");
      out.write("                            <table class=\"table\">\n");
      out.write("                                <tbody>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>First Name : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"fName\" name=\"fName\" value=\"");
      out.print(donar.getfName());
      out.write("\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Last Name : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"lName\" name=\"lName\" value=\"");
      out.print(donar.getlName());
      out.write("\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Address : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"");
      out.print(donar.getAddress());
      out.write("\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Blood Group : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <select name=\"bloodgroup\" class=\"form-select form-control\" id=\"bloodgroup\">\n");
      out.write("                                                <option selected=\"selected\">Choose option</option>\n");
      out.write("                                                <option>O+</option>\n");
      out.write("                                                <option>O-</option>\n");
      out.write("                                                <option>A+</option>\n");
      out.write("                                                <option>A-</option>\n");
      out.write("                                                <option>B+</option>\n");
      out.write("                                                <option>B-</option>\n");
      out.write("                                                <option>AB+</option>\n");
      out.write("                                                <option>AB-</option>\n");
      out.write("                                            </select>\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <input type=\"submit\" class=\"btn btn-outline-danger\" value=\"save\" data-bs-toggle=\"modal\" data-bs-target=\"#editModal\">\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"modal fade\" id=\"passwordModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog \">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header bg-red\">\n");
      out.write("                        <h1 class=\"modal-title fs-5 text-light text-center\" id=\"exampleModalLabel\"><i class=\"fas fa-solid fa-key fs-5\"></i> Change Password</h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close bg-light\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <form action=\"../../changePassword\" method=\"post\" id=\"changePassword\">\n");
      out.write("                            <input type=\"hidden\" name=\"dbPassword\" value=\"");
      out.print(donar.getPassword());
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( IdProvider.getDonarId(donar));
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"userType\" id=\"userType\" value=\"donar\">\n");
      out.write("                            <table class=\"table\">\n");
      out.write("                                <tbody>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Old Password : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" id=\"oldPassword\" name=\"oldPassword\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>New Password : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" id=\"newPassword\" name=\"newPassword\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <input type=\"submit\" class=\"btn btn-outline-danger\" value=\"change\" data-bs-toggle=\"modal\" data-bs-target=\"#passwordModal\">\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"asider\" style=\"width:222px\">\n");
      out.write("            <ul class=\"list-group list-unstyled\">\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarDashboard.jsp\"><i class=\"fas fa-home\"></i> Home</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodDonation.jsp\"><i class=\"fas fa-hand-holding-medical\"></i> Donate Blood</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodDonationHistory.jsp\"><i class=\"fas fa-history\"></i> Donation History</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodReq.jsp\"><i class=\"fas fa-sync-alt\"></i> Blood Request</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodReqHistory.jsp\"><i class=\"fas fa-history\"></i> Request History</a></li>\n");
      out.write("            </ul> \n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("<div class=\"bg-red text-light fixed-bottom text-center\">\n");
      out.write("    <p class=\"pt-1\"> Made In India &COPY; 2024</p>\n");
      out.write("</div>");
      out.write("\n");
      out.write("        <script src=\"https://unpkg.com/sweetalert2@7.8.2/dist/sweetalert2.all.js\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"../../static/js/changePassword.js\"></script>\n");
      out.write("        <script src=\"../../static/js/logout.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container\"  style=\"margin-left: 220px; margin-top: 75px;\">\n");
      out.write("            ");

                Donar currentDonar = (Donar) session.getAttribute("currentDonar");
                int id = IdProvider.getDonarId(currentDonar);
            
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <div class=\"card bg-light\">\n");
      out.write("                        <div class=\"card-body d-flex justify-content-between mb-3\">\n");
      out.write("                            <div class=\"blood\">\n");
      out.write("                                <i class=\"fas fa-sync-alt xyz text-primary fs-4\"></i>\n");
      out.write("                                <div class=\"mt-5 fs-5\">\n");
      out.write("                                    Request Made \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"position-relative fs-5\" style=\"top: 10px; right: 30px;\">\n");
      out.write("                                ");

                                    int count1 = CountProvider.getTotalCount("blood_donation_list_tb", "id", "donar_id", id);
                                    int count2 = CountProvider.getTotalCount("blood_request_list_tb", "id", "donar_id", id);
                                    int totalCount = count1 + count2;
                                    int dc = count1;
                                
      out.write("\n");
      out.write("                                ");
      out.print(totalCount);
      out.write("\n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <div class=\"card bg-light\">\n");
      out.write("                        <div class=\"card-body d-flex justify-content-between mb-3\">\n");
      out.write("                            <div class=\"blood\">\n");
      out.write("                                <i class=\"fas fa-sync xyz text-warning fs-4\"></i>\n");
      out.write("                                <div class=\"mt-5 fs-5\">\n");
      out.write("                                    Pending Request\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"position-relative fs-5\" style=\"top: 10px; right: 30px;\">\n");
      out.write("                                ");

                                    count1 = CountProvider.getCondCount("blood_donation_list_tb", "id", "Pending", "donar_id", id);
                                    count2 = CountProvider.getCondCount("blood_request_list_tb", "id", "Pending", "donar_id", id);
                                    totalCount = count1 + count2;
                                
      out.write("\n");
      out.write("                                ");
      out.print(totalCount);
      out.write("\n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <div class=\"card bg-light\">\n");
      out.write("                        <div class=\"card-body d-flex justify-content-between mb-3\">\n");
      out.write("                            <div class=\"blood\">\n");
      out.write("                                <i class=\"fas fa-check-circle text-primary fs-4\"></i>\n");
      out.write("                                <div class=\"mt-5 fs-5\">\n");
      out.write("                                    Approved Request\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"position-relative fs-5\" style=\"top: 10px; right: 30px;\">\n");
      out.write("                                ");

                                    count1 = CountProvider.getCondCount("blood_donation_list_tb", "id", "Approved", "donar_id", id);
                                    count2 = CountProvider.getCondCount("blood_request_list_tb", "id", "Approved", "donar_id", id);
                                    totalCount = count1 + count2;
                                
      out.write("\n");
      out.write("                                ");
      out.print(totalCount);
      out.write(" \n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row mt-2\">\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <div class=\"card bg-light\">\n");
      out.write("                        <div class=\"card-body d-flex justify-content-between mb-3\">\n");
      out.write("                            <div class=\"blood\">\n");
      out.write("                                <i class=\"fas fa-times-circle xyz text-danger fs-4\"></i>\n");
      out.write("                                <div class=\"mt-5 fs-5\">\n");
      out.write("                                    Rejected Request \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"position-relative fs-5\" style=\"top: 10px; right: 30px;\">\n");
      out.write("                                ");

                                    count1 = CountProvider.getCondCount("blood_donation_list_tb", "id", "Rejected", "donar_id", id);
                                    count2 = CountProvider.getCondCount("blood_request_list_tb", "id", "Rejected", "donar_id", id);
                                    totalCount = count1 + count2;
                                
      out.write("\n");
      out.write("                                ");
      out.print(totalCount);
      out.write("\n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <div class=\"card bg-light\">\n");
      out.write("                        <div class=\"card-body d-flex justify-content-between mb-3\">\n");
      out.write("                            <div class=\"blood\">\n");
      out.write("                                <i class=\"fas fa-check-circle text-success fs-4\"></i>\n");
      out.write("                                <div class=\"mt-5 fs-5\">\n");
      out.write("                                    Donated Successfully\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"position-relative fs-5\" style=\"top: 10px; right: 30px;\">\n");
      out.write("                                ");

                                    count1 = CountProvider.getCondCount("blood_donation_list_tb", "id", "Donated", "donar_id", id);
                                
      out.write("\n");
      out.write("                                ");
      out.print(count1);
      out.write(" \n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <div class=\"card bg-light\">\n");
      out.write("                        <div class=\"card-body d-flex justify-content-between mb-3\">\n");
      out.write("                            <div class=\"blood\">\n");
      out.write("                                <i class=\"fas fa-check-circle text-success fs-4\"></i>\n");
      out.write("                                <div class=\"mt-5 fs-5\">\n");
      out.write("                                    Withdrawal Successfully\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"position-relative fs-5\" style=\"top: 10px; right: 30px;\">\n");
      out.write("                                ");

                                    count2 = CountProvider.getCondCount("blood_request_list_tb", "id", "Withdrawal", "donar_id", id);
                                
      out.write("\n");
      out.write("                                ");
      out.print(count2);
      out.write(" \n");
      out.write("                            </div>                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <hr>\n");
      out.write("\n");
      out.write("            ");

                if (dc == 0) {
                    out.println("<div class='row mt-3'>");
                    out.println("<div class='col-6 offset-3'>");
                    out.println("<div class='card bg-light'>");
                    out.println("<div class='card-body text-center '>");
                    out.println("<div class='my-3 fs-4 text-primary'>");
                    out.println(" You Have Not Yet Made Any Donation Request !");
                    out.println("</div>");
                    out.println("<div>");
                    out.println("<p>For Donation Request </p>");
                    out.println("<a class='btn btn-danger' href='donarBloodDonation.jsp'>Made Request</a>");
                    out.println("</div>");
                    out.println("</div>");
                    out.println("</div>");
                    out.println("</div>");
                    out.println(" </div>");
                } else {
                    try {
                        String query = "SELECT status, approval_date, rejection_reason FROM blood_donation_list_tb WHERE donar_id = ? ORDER BY id desc LIMIT 1";
                        String status = "";
                        Date approvalDate;
                        String rejectionReason;
                        Connection con = DBClass.getConnection();
                        PreparedStatement pstmt = con.prepareStatement(query);
                        pstmt.setInt(1, id);
                        ResultSet rs = pstmt.executeQuery();
                        if (rs.next()) {
                            status = rs.getString("status");

                            if (status.equals("Approved")) {
                                approvalDate = rs.getDate("approval_date");
                                LocalDate localApprovalDate = approvalDate.toLocalDate();
                                LocalDate expireDate = localApprovalDate.plusDays(10);
                                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                                String formattedExpireDate = expireDate.format(formatter);
                                out.println("<div class='row mt-3'>");
                                out.println("<div class='col-6 offset-3'>");
                                out.println("<div class='card bg-light'>");
                                out.println("<div class='card-body text-center '>");
                                out.println("<div class='my-3 fs-4 text-primary'>");
                                out.println(" Your Request For Donation Has Been Approved !");
                                out.println("</div>");
                                out.println("<div>");
                                out.println("<p>You can visit our blood bank. </p>");
                                out.println("<p>Within 10 days you need to donate your blood. </p>");
                                out.println("<p class='text-danger'>Expired Date : " + formattedExpireDate + "</p>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println(" </div>");
                            } else if (status.equals("Rejected")) {
                                rejectionReason = rs.getString("rejection_reason");
                                out.println("<div class='row mt-3'>");
                                out.println("<div class='col-6 offset-3'>");
                                out.println("<div class='card bg-light'>");
                                out.println("<div class='card-body text-center '>");
                                out.println("<div class='my-3 fs-4 text-danger'>");
                                out.println("Your Request For Blood Has Been Rejected !");
                                out.println("</div>");
                                out.println("<div>");
                                out.println("<p>Sorry Try next time. </p>");
                                out.println("<p>Reason : " + rejectionReason + "</p>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println(" </div>");
                            } else if (status.equals("Donated")) {
                                out.println("<div class='row mt-3'>");
                                out.println("<div class='col-6 offset-3'>");
                                out.println("<div class='card bg-light'>");
                                out.println("<div class='card-body text-center '>");
                                out.println("<div class='my-3 fs-4 text-success'>");
                                out.println("Thank you for your valuable blood !");
                                out.println("</div>");
                                out.println("<div>");
                                out.println("<p>You can donate your blood 3 times in a year.</p>");
                                out.println("<p class='text-primary'>Eat healthy and stay strong !</p>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println(" </div>");
                            } else {
                                out.println("<div class='row mt-5'>");
                                out.println("<div class='col-6 offset-3'>");
                                out.println("<div class='card bg-light'>");
                                out.println("<div class='card-body text-center '>");
                                out.println("<div class='my-3 fs-4 text-warning'>");
                                out.println("Your Donation For Blood In Progress !");
                                out.println("</div>");
                                out.println("<div>");
                                out.println("<p class='text-primary'>Please wait for approval . </p>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println("</div>");
                                out.println(" </div>");
                            }
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
            
      out.write("\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
