/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2024-04-28 03:57:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template.donar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.helper.*;
import com.entities.Donar;
import com.entities.Donar;
import com.helper.IdProvider;

public final class donarBloodDonation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/template/donar/../../footer.html", Long.valueOf(1714229182147L));
    _jspx_dependants.put("/template/donar/../../header.jsp", Long.valueOf(1714229182147L));
    _jspx_dependants.put("/template/donar/donarBase.jsp", Long.valueOf(1714229182248L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("com.helper");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.helper.IdProvider");
    _jspx_imports_classes.add("com.entities.Donar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>OBBMS - Save The Lifes</title>\n");
      out.write("\n");
      out.write("        <!-- font awesome -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"\n");
      out.write("              integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\"\n");
      out.write("              crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("        <!--Bootstrap cdn-->\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("        <link href=\"../../static/css/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"../../static/img/logo.avif\" rel=\"icon\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <nav style=\"background-color: #FF0018;\" class=\"navbar navbar-expand-md navbar-dark fixed-top\">\n");
      out.write("            <div class=\"container-fluid d-flex justify-content-evenly\">\n");
      out.write("                <!-- Title -->\n");
      out.write("                <div class=\"navbar-brand fs-3 me-auto\"><i class=\"fas fa-heartbeat\"></i>&nbsp; Online Blood Bank Management System &nbsp;<i class=\"fas fa-heartbeat\"></i></div>\n");
      out.write("                <!-- Navbar Links -->\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li class=\"nav-item ms-5\">\n");
      out.write("                        <a class=\"nav-link fs-5 me-5\" style=\"color: white;\" data-bs-toggle=\"modal\" data-bs-target=\"#profileModal\" href=\"#?\"><i class=\"fas fa-user-circle\"></i> Profile</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("        <!-- Modal -->\n");
      out.write("        <div class=\"modal fade\" id=\"profileModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog \">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header bg-red\">\n");
      out.write("                        <h1 class=\"modal-title fs-5 text-light text-center\" id=\"exampleModalLabel\"><i class=\"fas fa-user-circle fs-5\"></i> Donar Profile</h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close bg-light\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        ");

                            Donar donar = (Donar) session.getAttribute("currentDonar");
                        
      out.write("\n");
      out.write("                        <table class=\"table\">\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Name : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getfName() + " " + donar.getlName());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Address : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getAddress());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Mobile No : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getMobno());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Blood Group : </th>\n");
      out.write("                                    <td>");
      out.print( donar.getBloodgroup());
      out.write("</td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <div class=\"d-flex justify-content-evenly\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#editModal\"><i class=\"fas fa-solid fa-user-pen\"></i> Edit</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-outline-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#passwordModal\"><i class=\"fas fa-solid fa-key\"></i> Change Password</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" onclick=\"logout('donarLogin')\"><i class=\"fas fa-sign-out-alt\"></i> Log out</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"modal fade\" id=\"editModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog \">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header bg-red\">\n");
      out.write("                        <h1 class=\"modal-title fs-5 text-light text-center\" id=\"exampleModalLabel\"><i class=\"fas fa-solid fa-user-pen fs-5\"></i> Edit Details </h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close bg-light\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <form action=\"../../editProfile\" method=\"post\" id=\"editProfile\">\n");
      out.write("                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( IdProvider.getDonarId(donar));
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"userType\" id=\"userType\" value=\"donar\">\n");
      out.write("                            <table class=\"table\">\n");
      out.write("                                <tbody>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>First Name : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"fName\" name=\"fName\" value=\"");
      out.print(donar.getfName());
      out.write("\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Last Name : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"lName\" name=\"lName\" value=\"");
      out.print(donar.getlName());
      out.write("\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Address : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"");
      out.print(donar.getAddress());
      out.write("\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Blood Group : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <select name=\"bloodgroup\" class=\"form-select form-control\" id=\"bloodgroup\">\n");
      out.write("                                                <option selected=\"selected\">Choose option</option>\n");
      out.write("                                                <option>O+</option>\n");
      out.write("                                                <option>O-</option>\n");
      out.write("                                                <option>A+</option>\n");
      out.write("                                                <option>A-</option>\n");
      out.write("                                                <option>B+</option>\n");
      out.write("                                                <option>B-</option>\n");
      out.write("                                                <option>AB+</option>\n");
      out.write("                                                <option>AB-</option>\n");
      out.write("                                            </select>\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <input type=\"submit\" class=\"btn btn-outline-danger\" value=\"save\" data-bs-toggle=\"modal\" data-bs-target=\"#editModal\">\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"modal fade\" id=\"passwordModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog \">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header bg-red\">\n");
      out.write("                        <h1 class=\"modal-title fs-5 text-light text-center\" id=\"exampleModalLabel\"><i class=\"fas fa-solid fa-key fs-5\"></i> Change Password</h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close bg-light\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <form action=\"../../changePassword\" method=\"post\" id=\"changePassword\">\n");
      out.write("                            <input type=\"hidden\" name=\"dbPassword\" value=\"");
      out.print(donar.getPassword());
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( IdProvider.getDonarId(donar));
      out.write("\">\n");
      out.write("                            <input type=\"hidden\" name=\"userType\" id=\"userType\" value=\"donar\">\n");
      out.write("                            <table class=\"table\">\n");
      out.write("                                <tbody>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Old Password : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" id=\"oldPassword\" name=\"oldPassword\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>New Password : </th>\n");
      out.write("                                        <td>\n");
      out.write("                                            <input type=\"password\" class=\"form-control\" id=\"newPassword\" name=\"newPassword\">\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <input type=\"submit\" class=\"btn btn-outline-danger\" value=\"change\" data-bs-toggle=\"modal\" data-bs-target=\"#passwordModal\">\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"asider\" style=\"width:222px\">\n");
      out.write("            <ul class=\"list-group list-unstyled\">\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarDashboard.jsp\"><i class=\"fas fa-home\"></i> Home</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodDonation.jsp\"><i class=\"fas fa-hand-holding-medical\"></i> Donate Blood</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodDonationHistory.jsp\"><i class=\"fas fa-history\"></i> Donation History</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodReq.jsp\"><i class=\"fas fa-sync-alt\"></i> Blood Request</a></li>\n");
      out.write("                <li class=\"px-3 d-block py-4 fs-5\"><a href=\"donarBloodReqHistory.jsp\"><i class=\"fas fa-history\"></i> Request History</a></li>\n");
      out.write("            </ul> \n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("<div class=\"bg-red text-light fixed-bottom text-center\">\n");
      out.write("    <p class=\"pt-1\"> Made In India &COPY; 2024</p>\n");
      out.write("</div>");
      out.write("\n");
      out.write("        <script src=\"https://unpkg.com/sweetalert2@7.8.2/dist/sweetalert2.all.js\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"../../static/js/changePassword.js\"></script>\n");
      out.write("        <script src=\"../../static/js/logout.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container\" style=\"margin-top: 75px;\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-4 offset-md-4\">\n");
      out.write("                    <div class=\"card\">\n");
      out.write("                        <div class=\"card-header bg-red text-light text-center fs-5\">\n");
      out.write("                            <i class=\"fas fa-hand-holding-medical fa-3x\"></i>&nbsp; \n");
      out.write("                            <p>Blood Donation</p>\n");
      out.write("                        </div>\n");
      out.write("                        ");

                            Donar currentDonar = (Donar) session.getAttribute("currentDonar");
                            int id = IdProvider.getDonarId(currentDonar);
                            String fName = currentDonar.getfName() + " " + currentDonar.getlName();
                            String dob = currentDonar.getDate();
                            String bloodgroup = currentDonar.getBloodgroup();
                            int age = AgeCalculator.getAge(dob);
                        
      out.write("\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("\n");
      out.write("                            <form class=\"row g-3\" action=\"../../donarBloodDonation\" method=\"POST\" id=\"donarForm\">\n");
      out.write("                                <input type=\"hidden\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\n");
      out.write("                                <input type=\"hidden\" name=\"dName\" value=\"");
      out.print(fName);
      out.write("\">\n");
      out.write("                                <input type=\"hidden\" name=\"bloodgroup\" value=\"");
      out.print( bloodgroup);
      out.write("\">\n");
      out.write("                                <input type=\"hidden\" name=\"age\" value=\"");
      out.print(age);
      out.write("\">\n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <label for=\"dName\" class=\"form-label\">Donar Name</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"dName\" name=\"dName\" value=\"");
      out.print(fName);
      out.write("\" disabled=\"disabled\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <label for=\"bloodgroup\" class=\"form-label\">Blood Group</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"bloodgroup\" name=\"bloodgroup\" value=\"");
      out.print( bloodgroup);
      out.write("\" disabled=\"disabled\">\n");
      out.write("                                </div>  \n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <label for=\"unit\" class=\"form-label\">Unit (in ml)</label>\n");
      out.write("                                    <input type=\"number\" class=\"form-control\" id=\"unit\" name=\"unit\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <label for=\"age\" class=\"form-label\">Donar Age</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"age\" name=\"age\" value=\"");
      out.print(age);
      out.write("\" disabled=\"disabled\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-12\">\n");
      out.write("                                    <label for=\"disease\" class=\"form-label\">Disease (if any)</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"disease\" name=\"disease\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"container text-center my-3\" style=\"display: none\" id=\"loader\">\n");
      out.write("                                    <span class=\"fa fa-refresh fa-spin fa-3x\" style=\"color: red\"></span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-12 text-center\">\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-danger btn-lg \" id=\"sign-btn\"> Donate </button>\n");
      out.write("                                </div>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <script src=\"../../static/js/donarDonation.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
